### ISSUE TITLE
link = "logit" causes additional category 

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#21]
Hey,

just to make sure: if I understand you correctly here: https://www.rdatagen.net/page/ordinal/
than it is intended to have n+1 categories for n "probabilities" when using logit link, as they are thresholds and not probabilities as when used with identity. 

Is this correct? If so we should add this into the documentation (maybe it's in there and im just blind :D) .

**Comment by kgoldfeld** [comment]
The user always specifies probabilities, not thresholds. If the sum of the n probabilities is less than one, then an n+1th category is created. So if probabilities were entered as c(.4, .2), then 3 categories would be created with probabilities (.4, .2, .4).  However if we originally specified c(..4, .6), then only two categories would be created. Is that what you were asking?

________________________________

**Comment by assignUser** [comment]
I am asking about this bit in `.gencat`: 
```r
  if (link == "logit") {
    parsedProbs <- exp(parsedProbs)
    parsedProbs <- parsedProbs  / (1 + rowSums(parsedProbs))
  }
```
When we take the formula: `".4;.6"`as in your example:
``` r
library(simstudy)
def <- defData(varname = "test", dist = "categorical", formula = ".4;.6", link = "logit")
dat <- genData(100,def)
head(dat)
#>    id test
#> 1:  1    2
#> 2:  2    2
#> 3:  3    3
#> 4:  4    1
#> 5:  5    2
#> 6:  6    1
range(dat$test)
#> [1] 1 3
```

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
We cat 3 and not 2 Categories. This is caused by the code earlier that caused the rowsum to not be 1

**Comment by assignUser** [comment]
(in your code `parsedProbs` is called `dtmatrix`) I did render this using the cran version of simstudy to make sure it was not a change I made that caused this.

**Comment by kgoldfeld** [comment]
Ah - I did not recall that I had permitted that. So, the values are indeed thresholds - so that is what is going on. And no, obviously, I did not explain that in the documentation. Good catch.

________________________________

**Comment by assignUser** [comment]
😁  Ok, we could keep the functionality the same then for compatibility? Or do you want to remove this and only allow probabilities?

**Comment by kgoldfeld** [comment]
Definitely keep the functionality. The idea is to allow for actual formulas rather than constants, so that the probability of group membership might depend on covariates - through a logit link in this case:


library(simstudy)

d <- defData(varname = "x", formula = 0.5, dist = "binary")
d <- defData(d, varname = "g", formula = c("-2+.4*x;-1+2*x"), dist="categorical",
        link = "logit")

dx <- genData(10000, d)

dx[, table(x, g)]
#>    g
#> x      1    2    3
#>   0  470 1191 3306
#>   1  276 3463 1294

Created on 2020-05-05 by the reprex package<https://reprex.tidyverse.org/> (v0.3.0)


________________________________

**Comment by assignUser** [comment]
Ok, I see. So if `link = "logit"`we do NOT (other then turning it into logit etc.) adjust the probabilities in case they sum to <1 or >1 right?

**Comment by kgoldfeld** [comment]
All the functions that use the logit link immediately convert the logit into a probability before the data are generated. That is what


dtmatrix <- exp(dtmatrix)
dtmatrix <- dtmatrix  / (1 + rowSums(dtmatrix))

is doing. dtmatrix is a matrix of probabilities.



The problem with the logit link is that it is virtually impossible to specify all the categorical probabilities on the logit scale (i.e so that they sum to 1), so that is why we need to adjust the probabilities or add a category after the conversion has been made.

________________________________

**Comment by assignUser** [comment]
Ah, right is was turned around, user specifies logit in formula and we convert to p, that makes more sense with exp() now too 😬. I know what to do now 👍 thanks for your quick counsel!
