### ISSUE TITLE
Create a longitudinal dataset is not just counting integers but reflects actual time points

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#222]
A user identified a possible enhancement to the function `addPeriods`. Right now, periods can only be defined as integers ranging from $0$ to $n-1$, so that there are $n$ periods. He wanted to be able to include specific time points in place of the integers. So, if the measurements are collected at baseline, 3 months, 6 months, and 12 months, the user should be able to replace $(0, 1, 2, 3)$ with $(0, 3, 6, 12)$.

**Comment by assignUser** [comment]
It might be useful to abstract a bit more and allow for full timestamps/epochs? But I don't really have the user context if that would be useful or just a waste of time getting it to work (in my experience timestamp stuff is notoriously difficult/tricky)

**Comment by kgoldfeld** [comment]
Not sure I am fully understanding. What exactly is a full timestamp or epoch?

**Comment by assignUser** [comment]
I was thinking of ISO 8601 timestamps: `2024-04-08T17:35:37Z` or [epoch timestamps](https://www.epochconverter.com/) (seconds since epoch, usually 1970-01-01): `1712600550` to specify concrete dates. But that might not be a useful (enough) addition to warrant the work to deal with  (e.g. likely adding a dependency on {lubridate})

**Comment by kgoldfeld** [comment]
Yeah - might be a little too specific. We can certainly think about that if someone came up with a case where that might be useful for their application. But for now, I will try to keep it relatively simple.
