### ISSUE TITLE
Rownames on probability matrix breaks genCorOrdCat

### ISSUE THREAD

**Issue by tkasci** [kgoldfeld/simstudy#23]
When adding row names to the base probability matrix, the function does not work anymore. Reproducible example: 

```
baseprobs.pre <- matrix(c(
 .336,.121,.543,0,0,
 .259,.237,.504,0,0,
 .462,.161,.377,0,0,
 .024,.165,.329,.412,.070,
 .141,.278,.395,.167,.019,
 .569,.197,.234,0,0,
 .727,.167,.106,0,0,
 .172,.155,.354,.314,.005,
 .513,.273,.178,.034,.002,
 .085,.090,.283,.478,.064,
 .152,.281,.567,0,0,
 .349,.188,.463,0,0,
 .504,.423,.071,.002,0,
 .385,.371,.197,.045,.002,
 .093,.386,.345,.168,.008,
 .536,.247,.181,.036,0,
 .979,.014,.007,0,0
),ncol = 5, byrow = T)

genCorOrdCat(data_pre, baseprobs = baseprobs.pre, rho = .2, corstr = "cs")

        id grp1 grp10 grp11 grp12 grp13 grp14 grp15 grp16 grp17 grp2 grp3 grp4 grp5 grp6 grp7 grp8 grp9
   1:    1    2     4     3     1     1     2     3     2     1    3    3    2    1    1    1    1    3

rownames(baseprobs.pre) <- c("H04","H05","H06","H01","H10","H12","H16","H02","H03","H07","H13","H14","H08","H09","H11","H15","H17") 

genCorOrdCat(data_pre, baseprobs = baseprobs.pre, rho = .2, corstr = "cs")

Error in genCorOrdCat(data_pre, baseprobs = baseprobs.pre, rho = 0.2,  : 
  Probabilities are not properly specified: each row must sum to one
```

**Comment by kgoldfeld** [comment]
Thanks for identifying this - we will definitely need to address that, as well as the ordering of default names.

**Comment by assignUser** [comment]
What is the intended behavior here? Should we just ignore row names? Or use them as names for the cat vars?
And ofc the columns should be ordered in a sensible manner.

**Comment by kgoldfeld** [comment]
I think we should just ignore the row names - I think it would be confusing otherwise. 

And yes, that is another flaw - if there are more than 10 columns, the numbers should be 2 digits so we would have grp01, grp02, ..., grp09, grp10. I guess if there were 100 columns, we would have to have 3 digits. (I am going to assume that we won't need more than 999.)

**Comment by assignUser** [comment]
Hm, but if we are merging the two functions I think it would make sense to allow rownames to name the var as it would be possible to create multiple, unrelated variables where a common name might not make sense and require either manual renaming after generation or  providing an additional vector with names (which we might still want as an option). Hm I'll tink about it and write something in a bit in #34  .

Zero padding shouldn't be too hard :)

**Comment by kgoldfeld** [comment]
I guess it doesn't really seem all that different, because to name the rows of a matrix, the user has to create a vector of names. That vector could just as easily be entered as an argument to our function.

So, I'll meet you halfway. We can allow the "catVar" argument to accept a vector of variable names (this exists in other simstudy functions) and keep the prefix argument. If catVar is specified, that overrides prefix. If catVar is NULL, the prefix functionality kicks in (and still defaults to "grp"). Note if user does not specify catVar or prefix, "grp" is used as a default prefix.

**Comment by assignUser** [comment]
Ok, it makes sense to keep it consistent across simstudy 👍
