### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#44]
I just uploaded a new version of the "Overview" vignette to the Vignette branch. We need to see if it can be generated with the package. Tell me what I need to do in order to facilitate that - such as generate the html file. And, I want to make sure that it passes all the rhub checks, because that was giving me a problem a couple years ago, and that is why I moved everything to my website.

If this one works, I can move all the other vignettes over as well, and improve on them, of course, over time.

And if you think the overview is still not good, let me know. One thing I considered was including R examples for each of the distributions, but thought that might be too much. But, it would be easy to add. And any other suggestions  would be welcome.

**Comment by assignUser** [comment]
I checked the vignette using the R-CMD-Manual action like this:
![image](https://user-images.githubusercontent.com/16141871/93773253-2e0d5480-fc20-11ea-9e04-93d160ece85b.png)

And found some issues: I seem to have accidentally removed the suggest for formatR which made the build fail because it is used to style the code by knitr. Additionally you used `data.table` without `library(data.table)` which worked on your end due to having it loaded by devtools. 

After those changes it worked well. I will add an action to automatically build vignettes when they have been changed :)

The new vignette looks great!

**Comment by kgoldfeld** [comment]
I uploaded the remaining vignettes (in the vignette branch). I haven't really edited the the older files - I definitely need to edit the ordinal data vignette to reflect what is likely to be the new unified function. This will give me a good opportunity to check that.

I don't fully understand how the vignettes get incorporated into the package. On my local build, I seem to have hit or miss success building and installing with the new vignettes.

**Comment by assignUser** [comment]
All of the vignettes build now except for the `ordinal.Rmd` one. There you use a functions called `odds()` do you remember which package that is from?

Vignettes are rendered when the package is build/packaged into a zip and live in the inst/doc folder. (and they are part of the pgkdown site) I think on cran they don't build the vignettes only running the related r code. 

A main issue with building vignettes is (on rhub & github actions) that you need to declare alle packages you use in them in suggests, otherwise the packages wont be installed and the vignette will fail. (which was the case here wit `gee` and `ordinal`)

**Comment by kgoldfeld** [comment]
I have my own personal package called `ksgMisc` which has a number of useful, simple functions. The odds function is the simplest (though I should probably check to make sure that 0 <= p < 1:

```r
odds <- function (p)  p/(1 - p) 
```

I guess we could create that function in simstudy - and could make it public or not.

**Comment by assignUser** [comment]
I updated the vignette branch and everything compiles without issues! I also locally build the pgkdown site with the new vignettes and documentation and it looks great. Do we want to update the README or do we want to keep it simple as it is now?

The only thing I would change is the vignette titles:
![image](https://user-images.githubusercontent.com/16141871/94160151-a411f580-fe84-11ea-9111-5e5915515c19.png)
I think removing "simstudy:" and converting to title case will look a bit smoother.

**Comment by kgoldfeld** [comment]
Maybe we can put the first part of the new intro vignette into the README, up until More Details ...

I agree with you on the vignette titles ...

**Comment by assignUser** [comment]
Yeah that looks good now: 
![image](https://user-images.githubusercontent.com/16141871/94249319-066c0400-ff20-11ea-9e1f-39e22aea5122.png)

I think the README is fine with the short intro, the overview vignette shows up as "Get Started" so that fits well.
Once I take care of #41 and #46 should we create a dedicated double-dot vignette to show off the advantages of this new feature?

**Comment by kgoldfeld** [comment]
Looks good. We could definitely do that - expanding on what is described in the overview. I had another idea for a useful function, particularly if you implment the vectorization. It could be nice to have a function `genMixFormula(functions, probs)` that takes two arguments - a vector of function names or a double-dot variable that is itself a vector and a vector of probabilities (which could be NULL, defaulting to equal probability *1/n* with *n* functions being mixed. 

Just something for one of us to think about in the future.

**Comment by assignUser** [comment]
I created an issue so we do not loose track of these ideas 👍
